enableSodiumMenu = true
useBlockStateCulling = true
useCustomItemFrameRenderer = false
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "CHECK"
leavesCullingDepth = 2
includeMangroveRoots = false
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
adorn = true
consistency_plus = true
wondrouswilds = true
terrestria = true
biomemakeover = true
traverse = true
earthtojavamobs = true
friendsandfoes = true
sod = true
minecraft = true
